# Generated by Django 4.2.4 on 2024-02-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='comment',
            field=models.CharField(default='No exceptions.', max_length=255),
        ),
    ]
